name: crawl
publish_to: none
environment:
  sdk: ">=2.0.0-dev <3.0.0"
dependencies:
  angel_framework: ^2.0.0-alpha.23
  angel_mongo: ^2.0.0
  # angel_sembast: ^1.0.0
  args: ^1.0.0
  canonical_url: ^1.0.0
  engine:
    path: ../engine
  html: ^0.13.0
  http: ^0.12.0
  http2_client: ^1.0.0
  isolate: ^2.0.0
  tuple: ^1.0.0
dependency_overrides:
  uuid: ^2.0.0